// apps/angular/src/app/components/rocket-selector.ts
import { Component, computed, signal, OnInit, model } from "@angular/core";
import { UiCombobox, type UiComboboxOption } from "./ui/ui-combobox";
import { Apollo, gql } from "apollo-angular";

import { ROCKET_CONFIGS } from "@orbitq/graphql";

type Rocket = {
  id: number;
  fullName: string;
  manufacturer: { name: string } | null;
};

type RocketConfigsQuery = {
  rocketConfigs: Rocket[];
};

@Component({
  selector: "rocket-selector",
  imports: [UiCombobox],
  template: `
    <section class="w-full px-6 py-3">
      @if (loading()) {
        <p class="font-mono text-orbitq-600 text-sm text-center">Loading...</p>
      } @else if (error()) {
        <p class="font-mono text-status-negative text-sm text-center">
          Failed to load rockets. Please try again later.
        </p>
      } @else {
        <div class="flex w-full">
          <div class="flex-1 flex items-center justify-center px-8">
            <ui-combobox
              class="w-full max-w-xs"
              placeholder="Select rocket A"
              listLabel="Rocket A options"
              toggleLabel="Open rocket A options"
              [displayValue]="displayA()"
              [open]="openA()"
              [options]="optionsA()"
              [selectedOptionId]="rocketA()?.id ?? null"
              [disabledOptionId]="rocketB()?.id ?? null"
              (queryChange)="queryA.set($event)"
              (openChange)="openA.set($event)"
              (optionSelected)="selectA($event)"
            />
          </div>

          <div class="flex-1 flex items-center justify-center px-8">
            @if (compareMode()) {
              <div class="flex gap-2 items-center w-full max-w-xs">
                <ui-combobox
                  class="flex-1"
                  placeholder="Select rocket B"
                  listLabel="Rocket B options"
                  toggleLabel="Open rocket B options"
                  [displayValue]="displayB()"
                  [open]="openB()"
                  [options]="optionsB()"
                  [selectedOptionId]="rocketB()?.id ?? null"
                  [disabledOptionId]="rocketA()?.id ?? null"
                  (queryChange)="queryB.set($event)"
                  (openChange)="openB.set($event)"
                  (optionSelected)="selectB($event)"
                />

                <button
                  type="button"
                  class="shrink-0 text-orbitq-600 hover:text-orbitq-50 transition-colors p-1"
                  aria-label="Remove comparison"
                  (click)="removeCompare()"
                >
                  <svg
                    class="h-4 w-4"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z"
                    />
                  </svg>
                </button>
              </div>
            } @else {
              <button
                type="button"
                class="font-mono text-sm border border-orbitq-700 text-orbitq-400 hover:text-orbitq-50 hover:border-orbitq-600 rounded-sm px-3 py-2 transition-colors whitespace-nowrap"
                (click)="compareMode.set(true)"
              >
                + Add to compare
              </button>
            }
          </div>
        </div>
      }
    </section>
  `,
})
export class RocketSelector implements OnInit {
  protected readonly loading = signal(false);
  protected readonly error = signal(false);
  protected readonly rockets = signal<Rocket[]>([]);

  constructor(private readonly apollo: Apollo) {}

  protected readonly queryA = signal("");
  protected readonly queryB = signal("");
  protected readonly openA = signal(false);
  protected readonly openB = signal(false);
  protected readonly compareMode = signal(false);

  rocketA = model<Rocket | null>(null);
  rocketB = model<Rocket | null>(null);

  ngOnInit() {
    this.loading.set(true);

    this.apollo
      .query<RocketConfigsQuery>({
        query: ROCKET_CONFIGS,
      })
      .subscribe({
        next: (result) => {
          if (result && result.data && result.data.rocketConfigs) {
            this.rockets.set(result.data.rocketConfigs);
            this.loading.set(false);
          }
        },
        error: (err) => {
          console.error("Error fetching rocket configs:", err);
          this.error.set(true);
          this.loading.set(false);
        },
      });
  }

  protected readonly optionsA = computed(() =>
    this.filterRockets(this.queryA()).map(toOption),
  );
  protected readonly optionsB = computed(() =>
    this.filterRockets(this.queryB()).map(toOption),
  );
  protected readonly displayA = computed(
    () => this.queryA() || this.rocketA()?.fullName || "",
  );
  protected readonly displayB = computed(
    () => this.queryB() || this.rocketB()?.fullName || "",
  );

  protected selectA(option: UiComboboxOption) {
    if (option.id === this.rocketB()?.id) return;
    this.rocketA.set(this.findRocket(option.id));
    this.queryA.set("");
    this.openA.set(false);
  }

  protected selectB(option: UiComboboxOption) {
    if (option.id === this.rocketA()?.id) return;
    this.rocketB.set(this.findRocket(option.id));
    this.queryB.set("");
    this.openB.set(false);
  }

  protected removeCompare() {
    this.compareMode.set(false);
    this.rocketB.set(null);
    this.queryB.set("");
    this.openB.set(false);
  }

  private filterRockets(query: string) {
    const q = query.trim().toLowerCase();
    if (!q) return this.rockets();
    return this.rockets().filter((rocket) =>
      rocket.fullName.toLowerCase().includes(q),
    );
  }

  private findRocket(id: number): Rocket | null {
    return this.rockets().find((rocket: Rocket) => rocket.id === id) ?? null;
  }
}

function toOption(rocket: Rocket): UiComboboxOption {
  return {
    id: rocket.id,
    label: rocket.fullName,
    description: rocket.manufacturer?.name,
  };
}

// apps/vue/src/components/RocketSelector.vue
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { useQuery } from "@vue/apollo-composable";
import { ROCKET_CONFIGS } from "@orbitq/graphql";
import type { RocketConfigsQuery } from "@orbitq/graphql";
import {
  Combobox,
  ComboboxInput,
  ComboboxButton,
  ComboboxOptions,
  ComboboxOption,
} from "@headlessui/vue";

type Rocket = RocketConfigsQuery["rocketConfigs"][number];

const { result, loading, error } = useQuery<RocketConfigsQuery>(ROCKET_CONFIGS);

const rocketA = defineModel<Rocket | null>("rocketA", { default: null });
const queryA = ref("");

const rocketB = defineModel<Rocket | null>("rocketB", { default: null });
const queryB = ref("");

const compareMode = ref(false);

// @headlessui/vue is still on v1 (v2 with the `immediate` prop is React-only).
// Clicking the button programmatically opens the listbox; the `open` slot prop
// guards against toggling it closed when it is already open.
const buttonA = ref<InstanceType<typeof ComboboxButton> | null>(null);
const buttonB = ref<InstanceType<typeof ComboboxButton> | null>(null);

watch(
  result,
  (val) => {
    if (rocketA.value === null) {
      const starshipV2 = val?.rocketConfigs.find((r) => r.id === 527) ?? null;
      rocketA.value = starshipV2;
    }
  },
  { once: true },
);

function filterRockets(query: string) {
  const rockets = result.value?.rocketConfigs ?? [];
  if (!query) return rockets;
  const q = query.toLowerCase();
  return rockets.filter((r) => r.fullName.toLowerCase().includes(q));
}

const filteredA = computed(() => filterRockets(queryA.value));
const filteredB = computed(() => filterRockets(queryB.value));

function handleSelectA(val: Rocket | null) {
  if (val === null) return;
  rocketA.value = val.id === rocketA.value?.id ? null : val;
}

function handleSelectB(val: Rocket | null) {
  if (val === null) return;
  rocketB.value = val.id === rocketB.value?.id ? null : val;
}

function removeCompare() {
  compareMode.value = false;
  rocketB.value = null;
  queryB.value = "";
}
</script>

<template>
  <section class="p-6 w-full flex flex-col items-center justify-center gap-6">
    <p v-if="loading" class="font-mono text-orbitq-600 text-sm">Loading…</p>
    <p v-else-if="error" class="font-mono text-status-negative text-sm">
      Error: {{ error.message }}
    </p>
    <div
      v-else
      class="flex items-center justify-around w-1/2"
      :class="{ 'gap-60': compareMode }"
    >
      <Combobox
        v-slot="{ open: openA }"
        :modelValue="rocketA"
        @update:modelValue="handleSelectA"
        nullable
        as="div"
        class="relative flex-1"
      >
        <div class="relative">
          <ComboboxInput
            class="w-full border border-orbitq-700 text-orbitq-50 font-mono text-sm rounded-sm px-3 py-2 pr-8 focus:outline-none focus:border-orbitq-600 transition-colors placeholder:text-orbitq-600"
            :displayValue="(r: unknown) => (r as Rocket | null)?.fullName ?? ''"
            placeholder="Select rocket A"
            @focus="
              () => {
                queryA = '';
                if (!openA) buttonA?.$el.click();
              }
            "
            @change="
              (e: Event) => {
                queryA = (e.target as HTMLInputElement).value;
                if (!openA) buttonA?.$el.click();
              }
            "
          />
          <ComboboxButton
            ref="buttonA"
            class="absolute inset-y-0 right-0 flex items-center pr-2 text-orbitq-600 hover:text-orbitq-50 transition-colors"
          >
            <svg
              class="h-4 w-4"
              viewBox="0 0 20 20"
              fill="currentColor"
              aria-hidden="true"
            >
              <path
                fill-rule="evenodd"
                d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
                clip-rule="evenodd"
              />
            </svg>
          </ComboboxButton>
        </div>
        <ComboboxOptions
          class="absolute z-10 mt-0.5 w-full bg-orbitq-850 border border-orbitq-700 rounded-sm py-1 shadow-lg max-h-60 overflow-auto focus:outline-none"
        >
          <ComboboxOption
            v-for="rocket in filteredA"
            :key="rocket.id"
            :value="rocket"
            :disabled="rocket.id === rocketB?.id"
            v-slot="{ active, selected, disabled }"
          >
            <div
              :class="[
                'flex flex-col gap-0.5 px-3 py-2',
                disabled ? 'cursor-not-allowed opacity-40' : 'cursor-pointer',
                active && !disabled && 'bg-orbitq-700',
              ]"
            >
              <span
                :class="[
                  'font-mono text-sm text-orbitq-50',
                  selected && 'font-semibold',
                ]"
              >
                {{ rocket.fullName }}
              </span>
              <span
                v-if="rocket.manufacturer"
                class="font-mono text-xs text-orbitq-600"
              >
                {{ rocket.manufacturer.name }}
              </span>
            </div>
          </ComboboxOption>
          <p
            v-if="filteredA.length === 0"
            class="px-3 py-2 font-mono text-sm text-orbitq-600"
          >
            No results
          </p>
        </ComboboxOptions>
      </Combobox>

      <template v-if="compareMode">
        <div class="flex gap-2 items-center flex-1">
          <Combobox
            v-slot="{ open: openB }"
            :modelValue="rocketB"
            @update:modelValue="handleSelectB"
            nullable
            as="div"
            class="relative flex-1"
          >
            <div class="relative">
              <ComboboxInput
                class="w-full border border-orbitq-700 text-orbitq-50 font-mono text-sm rounded-sm px-3 py-2 pr-8 focus:outline-none focus:border-orbitq-600 transition-colors placeholder:text-orbitq-600"
                :displayValue="
                  (r: unknown) => (r as Rocket | null)?.fullName ?? ''
                "
                placeholder="Select rocket B"
                @focus="
                  () => {
                    queryB = '';
                    if (!openB) buttonB?.$el.click();
                  }
                "
                @change="
                  (e: Event) => {
                    queryB = (e.target as HTMLInputElement).value;
                    if (!openB) buttonB?.$el.click();
                  }
                "
              />
              <ComboboxButton
                ref="buttonB"
                class="absolute inset-y-0 right-0 flex items-center pr-2 text-orbitq-600 hover:text-orbitq-50 transition-colors"
              >
                <svg
                  class="h-4 w-4"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  aria-hidden="true"
                >
                  <path
                    fill-rule="evenodd"
                    d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
                    clip-rule="evenodd"
                  />
                </svg>
              </ComboboxButton>
            </div>
            <ComboboxOptions
              class="absolute z-10 mt-0.5 w-full bg-orbitq-850 border border-orbitq-700 rounded-sm py-1 shadow-lg max-h-60 overflow-auto focus:outline-none"
            >
              <ComboboxOption
                v-for="rocket in filteredB"
                :key="rocket.id"
                :value="rocket"
                :disabled="rocket.id === rocketA?.id"
                v-slot="{ active, selected, disabled }"
              >
                <div
                  :class="[
                    'flex flex-col gap-0.5 px-3 py-2',
                    disabled
                      ? 'cursor-not-allowed opacity-40'
                      : 'cursor-pointer',
                    active && !disabled && 'bg-orbitq-700',
                  ]"
                >
                  <span
                    :class="[
                      'font-mono text-sm text-orbitq-50',
                      selected && 'font-semibold',
                    ]"
                  >
                    {{ rocket.fullName }}
                  </span>
                  <span
                    v-if="rocket.manufacturer"
                    class="font-mono text-xs text-orbitq-600"
                  >
                    {{ rocket.manufacturer.name }}
                  </span>
                </div>
              </ComboboxOption>
              <p
                v-if="filteredB.length === 0"
                class="px-3 py-2 font-mono text-sm text-orbitq-600"
              >
                No results
              </p>
            </ComboboxOptions>
          </Combobox>
          <button
            class="shrink-0 text-orbitq-600 hover:text-orbitq-50 transition-colors p-1"
            aria-label="Remove comparison"
            @click="removeCompare"
          >
            <svg
              class="h-4 w-4"
              viewBox="0 0 20 20"
              fill="currentColor"
              aria-hidden="true"
            >
              <path
                d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z"
              />
            </svg>
          </button>
        </div>
      </template>

      <button
        v-else
        class="shrink-0 font-mono text-sm border border-orbitq-700 text-orbitq-400 hover:text-orbitq-50 hover:border-orbitq-600 rounded-sm px-3 py-2 transition-colors whitespace-nowrap"
        @click="compareMode = true"
      >
        + Add to compare
      </button>
    </div>
  </section>
</template>
