// apps/vue/src/App.vue
<script setup lang="ts">
import { useQuery } from '@vue/apollo-composable'
import { ROCKET_CONFIGS_BY_IDS } from '@orbitq/graphql'
import type { RocketConfigsByIdsQuery, RocketConfigsByIdsVariables } from '@orbitq/graphql'

const SMOKE_TEST_IDS = [164, 121]

const { result, loading, error } = useQuery<RocketConfigsByIdsQuery, RocketConfigsByIdsVariables>(
  ROCKET_CONFIGS_BY_IDS,
  { ids: SMOKE_TEST_IDS },
)
</script>

<template>
  <div>
    <h1>OrbitQ Explorer</h1>
    <p v-if="loading">Loading rockets…</p>
    <p v-else-if="error">Error: {{ error.message }}</p>
    <ul v-else>
      <li v-for="rocket in result?.rocketConfigsByIds" :key="rocket.id">
        {{ rocket.fullName }}
      </li>
    </ul>
  </div>
</template>

// src/App.tsx
import { useQuery } from '@apollo/client/react'
import { ROCKET_CONFIGS_BY_IDS } from './graphql/queries'
import type { RocketConfigsByIdsQuery, RocketConfigsByIdsVariables } from './graphql/types'

// Smoke test: Falcon 9 Block 5 (164) vs Ariane 62 (121) — remove when canvas is wired up
const SMOKE_TEST_IDS = [164, 121];

export default function App() {
  const { data, loading, error } = useQuery<RocketConfigsByIdsQuery, RocketConfigsByIdsVariables>(
    ROCKET_CONFIGS_BY_IDS,
    { variables: { ids: SMOKE_TEST_IDS } },
  );

  if (loading) return <p>Loading rockets…</p>;
  if (error) return <p>Error: {error.message}</p>;

  return (
    <div>
      <h1>OrbitQ Explorer</h1>
      <ul>
        {data?.rocketConfigsByIds.map(r => (
          <li key={r.id}>{r.fullName}</li>
        ))}
      </ul>
    </div>
  )
}
